# Generated by Django 4.2.4 on 2023-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('ugolovnyi', 'Уголовный кодекс'), ('semeinyi', 'Семейный кодекс'), ('nalogovyi', 'Налоговый кодекс'), ('grajdanskyi', 'Гражданский кодекс'), ('trudovoyi', 'Трудовой кодекс'), ('budjetnyi', 'Бюджетный кодекс')], max_length=255, null=True),
        ),
    ]
